version: '3'

services:
  mongodb:
      image: mongo:7.0.16
      ports:
        - "27017:27017"
      env_file:
        - ../../.env
      volumes:
        - 'dev-mongodb:/data/db'
        - '../../src/main/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh'
      networks:
        - dev-network
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - 'redis_data:/data'
volumes:
  dev-mongodb:
    driver: local
  redis_data:
    driver: local
networks:
  dev-network:
    driver: bridge