version: '3'

services:
  mongodb:
      image: mongo:7.0.16
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-testUser}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-testPassword}
        MONGO_INITDB_DATABASE: ${DATABASE_NAME:-space_db}
      volumes:
        - 'space-mongodb:/data/db'
        - '../../src/main/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh'
      networks:
        - space-network
  redis:
    image: redis:7.4.2
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - 'redis_data:/data'
    networks:
      - space-network
  server:
    restart: always
    container_name: space-server
    build:
        context: ../../
        dockerfile: ./docker/production/Dockerfile
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    env_file:
      - ../../.env
    environment:
      NODE_ENV: production
      SERVER_PORT: ${SERVER_PORT:-3000}
      BASE_URL_PATH: ${BASE_URL_PATH}
      MONGO_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-testUser}
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-testPassword}
      MONGO_URI: mongodb://${DATABASE_USERNAME:-testUser}:${DATABASE_PASSWORD:-testUser}@mongodb:27017/${DATABASE_NAME:-space_db}
      REDIS_URL: redis://redis:6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_SALT: ${JWT_SALT}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-space4all}
    volumes:
      - 'space-statics:/usr/src/server/public'
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis
    networks:
      - space-network
volumes:
  space-mongodb:
    driver: local
  space-statics:
    driver: local
  redis_data:
    driver: local
networks:
  space-network:
    driver: bridge