name: Integration Tests Run
on:
  pull_request:
    branches:
      - develop'
      - 'main'
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_ENVIRONMENT: "production"
          envkey_DATABASE_TECHNOLOGY: "mongoDB"
          envkey_MONGO_PROTOCOL: "mongodb"
          envkey_MONGO_HOST: "localhost"
          envkey_MONGO_PORT: ${{ vars.CI_MONGO_PORT }}
          envkey_MONGO_INITDB_DATABASE: ${{ vars.CI_MONGO_INITDB_DATABASE }}
          envkey_MONGO_INITDB_ROOT_USERNAME: ${{vars.CI_MONGO_INITDB_ROOT_USERNAME}}
          envkey_MONGO_INITDB_ROOT_PASSWORD: ${{vars.CI_MONGO_INITDB_ROOT_PASSWORD}}
          envkey_DATABASE_NAME: ${{ vars.CI_MONGO_INITDB_DATABASE }}
          envkey_DATABASE_USERNAME: ${{vars.CI_MONGO_INITDB_ROOT_USERNAME}}
          envkey_DATABASE_PASSWORD: ${{vars.CI_MONGO_INITDB_ROOT_PASSWORD}}
          envkey_SERVER_PORT: "8080"
          envkey_BASE_URL_PATH: "/api"
          # envkey_ADMIN_PASSWORD: secrets.ADMIN_PASSWORD
          # envkey_USER_PASSWORD: secrets.USER_PASSWORD
          envkey_REDIS_URL: "redis://localhost:6379"
          envkey_JWT_SECRET: ${{ secrets.CI_JWT_SECRET }}
          envkey_JWT_EXPIRATION: "1h"
          envkey_JWT_SALT: ${{ secrets.CI_JWT_SALT }}
          
          directory: .
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Start MongoDBs
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '7.0.16'
          mongodb-username: ${{ vars.CI_MONGO_INITDB_ROOT_USERNAME }}
          mongodb-password: ${{ vars.CI_MONGO_INITDB_ROOT_PASSWORD }}
          mongodb-db: ${{ vars.CI_MONGO_INITDB_DATABASE }}
          mongodb-port: ${{ vars.CI_MONGO_PORT }}

      - name: Start Redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: '7.x'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test:ci
